import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsDate, IsOptional, IsString, MaxLength } from 'class-validator';

export class CreateRevisionDto {
  @ApiPropertyOptional({
    example: '000',
    description: 'Optional. Generated by the API when omitted.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  revision_number?: string;

  @ApiPropertyOptional({ example: 'Updated approval section.' })
  @IsOptional()
  @IsString()
  reason_of_revision?: string;

  @ApiPropertyOptional({ example: '2026-07-04T00:00:00.000Z' })
  @IsOptional()
  @Type(() => Date)
  @IsDate()
  effective_date?: Date;

  @ApiPropertyOptional({ example: '1-5' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  page_number?: string;

  @ApiPropertyOptional({ example: 'SERIES-2026-01' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  series_number?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(50)
  revision_level_from?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(50)
  revision_level_to?: string;

  @ApiPropertyOptional({ example: '2026-07-04T00:00:00.000Z' })
  @IsOptional()
  @Type(() => Date)
  @IsDate()
  previous_effective_date?: Date;

  @ApiPropertyOptional({ example: '2026-08-29T00:00:00.000Z' })
  @IsOptional()
  @Type(() => Date)
  @IsDate()
  new_effective_date?: Date;

  @ApiProperty({ example: '1', description: 'Uploader user ID as a string.' })
  @IsString()
  uploaded_by: string;

  @ApiPropertyOptional({ example: 'true' })
  @IsOptional()
  @IsString()
  set_as_current?: string;

  @ApiPropertyOptional({ description: 'Revision ID being corrected or replaced. The prior file remains preserved.' })
  @IsOptional()
  @IsString()
  superseded_by_revision_id?: string;

  @ApiPropertyOptional({ description: 'Required explanation for a controlled file correction or replacement.' })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  correction_reason?: string;
}
