-- Consolidate roles without changing account IDs or dropping workflow history.
INSERT INTO roles (role_name, description) VALUES ('Admin', 'Admin system role') ON DUPLICATE KEY UPDATE role_name=VALUES(role_name);
INSERT INTO roles (role_name, description) VALUES ('Internal Audit', 'Internal Audit system role') ON DUPLICATE KEY UPDATE role_name=VALUES(role_name);
INSERT INTO roles (role_name, description) VALUES ('Documentation Officer', 'Documentation Officer system role') ON DUPLICATE KEY UPDATE role_name=VALUES(role_name);
INSERT INTO roles (role_name, description) VALUES ('Staff', 'Staff system role') ON DUPLICATE KEY UPDATE role_name=VALUES(role_name);
INSERT INTO roles (role_name, description) VALUES ('Plant Manager', 'Plant Manager system role') ON DUPLICATE KEY UPDATE role_name=VALUES(role_name);
CREATE TEMPORARY TABLE role_remap (old_id BIGINT PRIMARY KEY, new_id BIGINT NOT NULL);
INSERT INTO role_remap SELECT old.role_id, target.role_id FROM roles old JOIN roles target ON target.role_name = CASE
 WHEN LOWER(REPLACE(old.role_name, ' ', '')) IN ('admin','administrator','superadmin','super-admin') THEN 'Admin'
 WHEN old.role_name IN ('Viewer','Internal Audit') THEN 'Internal Audit'
 WHEN old.role_name IN ('Document Controller','Documentation Officer') THEN 'Documentation Officer'
 WHEN old.role_name = 'Plant Manager' THEN 'Plant Manager'
 ELSE 'Staff' END WHERE old.role_name NOT IN ('Admin','Internal Audit','Documentation Officer','Staff','Plant Manager');
UPDATE users t JOIN role_remap m ON t.role_id=m.old_id SET t.role_id=m.new_id;
UPDATE account_registration_requests t JOIN role_remap m ON t.requested_role_id=m.old_id SET t.requested_role_id=m.new_id;
UPDATE account_registration_requests t JOIN role_remap m ON t.assigned_role_id=m.old_id SET t.assigned_role_id=m.new_id;
UPDATE document_workflow_steps t JOIN role_remap m ON t.assigned_role_id=m.old_id SET t.assigned_role_id=m.new_id;
DELETE rp FROM role_permissions rp JOIN role_remap m ON rp.role_id=m.old_id;
DELETE r FROM roles r JOIN role_remap m ON r.role_id=m.old_id;
DROP TEMPORARY TABLE role_remap;
DELETE FROM role_permissions;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.role_id, p.permission_id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Admin';
INSERT INTO role_permissions (role_id, permission_id) SELECT r.role_id, p.permission_id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Internal Audit' AND p.permission_name IN ('activity-logs.view_logs','dashboard.view','documents.download','documents.search','documents.view','softcopy-folders.view');
INSERT INTO role_permissions (role_id, permission_id) SELECT r.role_id, p.permission_id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Documentation Officer' AND p.permission_name IN ('ai-document-assistant.search','dashboard.view','document-access-requests.approve','document-access-requests.cancel-own','document-access-requests.catalog','document-access-requests.create','document-access-requests.expire','document-access-requests.grant','document-access-requests.reject','document-access-requests.review','document-access-requests.revoke','document-access-requests.view-own','document-disposal.request','document-requests.approve-document-controller','document-requests.approve-hardcopy','document-requests.complete','document-requests.create','document-requests.edit','document-requests.reject','document-requests.request-revision','document-requests.review','document-requests.submit','document-requests.view','document-requests.view-own','documents.attach-scans','documents.create','documents.download','documents.manage-own','documents.search','documents.view','hardcopy-transfers.accept','hardcopy-transfers.approve','hardcopy-transfers.create','hardcopy-transfers.dispatch','hardcopy-transfers.review','hardcopy-transfers.view-own','softcopy-folders.create','softcopy-folders.edit','softcopy-folders.view');
INSERT INTO role_permissions (role_id, permission_id) SELECT r.role_id, p.permission_id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Staff' AND p.permission_name IN ('ai-document-assistant.search','dashboard.view','document-access-requests.cancel-own','document-access-requests.catalog','document-access-requests.create','document-access-requests.view-own','document-disposal.request','document-requests.create','document-requests.edit','document-requests.submit','document-requests.view','document-requests.view-own','documents.attach-scans','documents.create','documents.download','documents.manage-own','documents.search','documents.view','hardcopy-transfers.accept','hardcopy-transfers.create','hardcopy-transfers.view-own','softcopy-folders.create','softcopy-folders.edit','softcopy-folders.view');
INSERT INTO role_permissions (role_id, permission_id) SELECT r.role_id, p.permission_id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Plant Manager' AND p.permission_name IN ('ai-document-assistant.search','dashboard.view','document-access-requests.approve','document-access-requests.cancel-own','document-access-requests.catalog','document-access-requests.create','document-access-requests.expire','document-access-requests.grant','document-access-requests.reject','document-access-requests.review','document-access-requests.revoke','document-access-requests.view-own','document-disposal.request','document-requests.approve-plant-manager','document-requests.complete','document-requests.create','document-requests.edit','document-requests.reject','document-requests.request-revision','document-requests.review','document-requests.submit','document-requests.view','document-requests.view-own','documents.attach-scans','documents.create','documents.download','documents.manage-own','documents.search','documents.view','hardcopy-transfers.accept','hardcopy-transfers.approve','hardcopy-transfers.create','hardcopy-transfers.dispatch','hardcopy-transfers.review','hardcopy-transfers.view-own','softcopy-folders.create','softcopy-folders.edit','softcopy-folders.view');
